version: '3.3'

services:
  app_data:
    build: dev-ops/docker/containers/ssh
    volumes:
        - app_server_data:/app
    ports:
        - "2222:22"
  app_server:
    build: dev-ops/docker/containers/app
    links:
      - app_mysql:mysql
    extra_hosts:
      - "docker.vm:127.0.0.1"
    volumes:
      - app_server_data:/app
      - ~/.composer:/.composer
      - ~/.npm:/.npm
    tmpfs:
      - /tmp:mode=1777

  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - app_server_mysql:/var/lib/mysql

volumes:
  app_server_data:
    external: true
  app_server_mysql:
    external: true
